version: "2"

services:

  postgres:
    image: postgres:9.6
    ports:
      - "8432:5432"
    volumes:
      - ./init:/docker-entrypoint-initdb.d

  tomcat:
    image: tomcat:7
    ports:
      - "8888:8080"
    depends_on:
      - postgres